name: Build and Deploy Calculator

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    # Optional: Install HTMLHint for linting (if you add a .htmlhintrc file)
    - name: Install dependencies
      run: npm install -g htmlhint

    - name: Lint HTML files
      run: htmlhint . --ext .html || true

    # Optional: Deploy to GitHub Pages (if you have a /docs folder or built output)
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # change to ./docs or ./dist if using build output

