version: 0.2
os: linux   # Use 'linux' for Ubuntu, not 'ubuntu'

files:
  - source: /
    destination: /var/www/html
    overwrite: true

hooks:
  AfterInstall:
    - location: scripts/postScript.sh   # Correct relative path
      timeout: 300
      runas: root
