version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user   # Target directory
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/preScript.sh    # Correct relative path
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/postScript.sh   # Correct relative path
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root